-- Typy danych 

CREATE OR REPLACE TYPE UCZESTNICY_DATA AS OBJECT (
  ID_OSOBY      INT
, ID_WYCIECZKI  INT
, NAZWA         VARCHAR2(100)
, KRAJ          VARCHAR2(50)
, "DATA"        DATE
, IMIE          VARCHAR2(50)
, NAZWISKO      VARCHAR2(50)
, STATUS        CHAR(1)
);

CREATE OR REPLACE TYPE UCZESTNICY_TABLE IS TABLE OF UCZESTNICY_DATA;


CREATE OR REPLACE TYPE WYCIECZKI_DATA AS OBJECT (
  ID_WYCIECZKI              INT
, NAZWA                     VARCHAR2(100)
, KRAJ                      VARCHAR2(50)
, "DATA"                    DATE
, OPIS                      VARCHAR2(100)
, LICZBA_MIEJSC             INT
, POZOSTALA_LICZBA_MIEJSC   INT
);

CREATE OR REPLACE TYPE WYCIECZKI_TABLE IS TABLE OF WYCIECZKI_DATA;

-- Funkcje

-- Uczestnicy_wycieczki

CREATE OR REPLACE FUNCTION UCZESTNICY_WYCIECZKI(ID INT) RETURN UCZESTNICY_TABLE
AS
    v_ret UCZESTNICY_TABLE;
    trip_not_found EXCEPTION;
    trip_count INT;
BEGIN
    SELECT COUNT(*) INTO trip_count FROM WYCIECZKI WHERE WYCIECZKI.ID_WYCIECZKI = ID;
    IF trip_count = 0 THEN
        RAISE trip_not_found;
    END IF;
    SELECT UCZESTNICY_DATA(v.ID_OSOBY, v.ID_WYCIECZKI, v.NAZWA, v.KRAJ, v.DATA, v.IMIE,
                             v.NAZWISKO, v.STATUS)
    BULK COLLECT INTO v_ret
    FROM WYCIECZKI_OSOBY v WHERE v.ID_WYCIECZKI = ID AND v.STATUS <> 'A';
RETURN v_ret;
END UCZESTNICY_WYCIECZKI;

-- rezerwacje_osoby

CREATE OR REPLACE FUNCTION REZERWACJE_OSOBY(ID INT) RETURN UCZESTNICY_TABLE
AS
    v_ret UCZESTNICY_TABLE;
    id_not_found EXCEPTION;
    id_count INT;
BEGIN
    SELECT COUNT(*) INTO id_count FROM OSOBY o WHERE o.ID_OSOBY = ID;
    IF id_count = 0 THEN
        RAISE id_not_found;
    END IF;
    SELECT UCZESTNICY_DATA(v.ID_OSOBY, v.ID_WYCIECZKI, v.NAZWA, v.KRAJ, v.DATA, v.IMIE,
                             v.NAZWISKO, v.STATUS)
    BULK COLLECT INTO v_ret
    FROM WYCIECZKI_OSOBY v WHERE v.ID_OSOBY = ID;
RETURN v_ret;
END REZERWACJE_OSOBY;

-- przyszłe rezerwacje_osoby

CREATE OR REPLACE FUNCTION PRZYSZLE_REZERWACJE_OSOBY(ID INT) RETURN UCZESTNICY_TABLE
AS
    v_ret UCZESTNICY_TABLE;
    id_not_found EXCEPTION;
    id_count INT;
BEGIN
    SELECT COUNT(*) INTO id_count FROM OSOBY o WHERE o.ID_OSOBY = ID;
    IF id_count = 0 THEN
        RAISE id_not_found;
    END IF;
    SELECT UCZESTNICY_DATA(v.ID_OSOBY, v.ID_WYCIECZKI, v.NAZWA, v.KRAJ, v.DATA, v.IMIE,
                             v.NAZWISKO, v.STATUS)
    BULK COLLECT INTO v_ret
    FROM WYCIECZKI_OSOBY v WHERE v.ID_OSOBY = ID AND v.STATUS <> 'A' AND v.DATA > CURRENT_DATE;
RETURN v_ret;
END PRZYSZLE_REZERWACJE_OSOBY;

-- dostepne_wycieczki

CREATE OR REPLACE FUNCTION DOSTEPNE_WYCIECZKI_KRAJ(KR VARCHAR, OD DATE, DO DATE) RETURN WYCIECZKI_TABLE
AS
    v_ret WYCIECZKI_TABLE;
    country_not_found EXCEPTION;
    wrong_date EXCEPTION;
    country_count INT;
BEGIN
    SELECT COUNT(*) INTO country_count FROM WYCIECZKI w WHERE w.KRAJ = KR;
    IF country_count = 0 THEN
        RAISE country_not_found;
    END IF;

    IF OD > DO THEN
        RAISE wrong_date;
    END IF;

    IF DO < CURRENT_DATE THEN
        RAISE wrong_date;
    END IF;

    SELECT WYCIECZKI_DATA(v.ID_WYCIECZKI, v.NAZWA, v.KRAJ, v.DATA, v.OPIS, v.LICZBA_MIEJSC, v.liczba_wolnych_miejsc)
    BULK COLLECT INTO v_ret
    FROM WYCIECZKI_MIEJSCA v WHERE v.LICZBA_WOLNYCH_MIEJSC > 0 AND v.KRAJ = KR AND v.DATA BETWEEN OD AND DO;
RETURN v_ret;
END DOSTEPNE_WYCIECZKI_KRAJ;
